FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
# toolchain
RUN apt-get install -yq cmake extra-cmake-modules g++ git gettext
# kf5 and qt5 libraries
RUN apt-get install -yq libkf5i18n-dev libkf5notifications-dev libkf5service-dev \
      libkf5windowsystem-dev libkf5plasma-dev qtbase5-dev qtdeclarative5-dev \
      plasma-framework

# required by tests
RUN apt-get install -yq xvfb
